spring:
  application:
    name: Ling-ai-agent
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ling_ai_agent}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        enabled: false
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        initialize-schema: true

server:
  port: 8123
  servlet:
    context-path: /api

search-api:
  api-key: ${SEARCH_API_KEY}