spring:
  application:
    name: Ling-ai-agent
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/ling_ai_agent
    username: postgres
    password: postgres
  ai:
    chat:
      client:
        observations:
          include-input: true
          include-output: true
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
      embedding:
        options:
          model: text-embedding-3-small
    mcp:
      client:
        request-timeout: 60s
        #sse:
        #  connections:
        #    server1:
        #      url: http://localhost:8127
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        initialize-schema: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  otlp:
    tracing:
      endpoint: https://api.smith.langchain.com/otel/v1/traces
      headers:
        x-api-key: ${LANGSMITH_API_KEY}
        langsmith-project: ling-ai-agent

server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ling.lingaiagent.controller
  show-actuator: false

knife4j:
  enable: true
  setting:
    language: zh_cn

search-api:
  api-key: pVEekXeWWe72tguRwE6ziXGY